###

GET http://localhost:3000/denuncias/2


###

POST http://localhost:3000/usuarios
Content-Type: application/json

{
    "nome": "Eduardo",
    "senha": "321",
    "email": "eduardo@gmail.com",
    "telefone": "48444444444"
}
